# Grunt aliases
---
# Build everything
build:
  - 'build:js'
  - 'build:i18n'

# Build JavaScript from assets to production
'build:js':
  - 'uglify'
# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'
  - 'glotpress_download'

# Check health of the project
check:
  - 'check:js'
  - 'check:php'
  - 'check:i18n'
'check:js':
  - 'jshint'
  - 'jsonlint'
  - 'jsvalidate'
  - 'jscs'
'check:php':
  - 'phplint'
  - 'phpcs'
'check:i18n':
  - 'checktextdomain'

# Create a zipped artifact from a fresh build
'artifact':
  - 'update-version'
  - 'shell:production-composer-install'
  - 'build'
  - 'clean:artifact'
  - 'copy:artifact'
  - 'compress:artifact'

# Default task
default:
  - build
